name: Ensure Project fields

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  setup-project-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure fields (Status, Priority, Area)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          script: |
            const owner = 'maple-buice';
            const number = 1; // your user project number

            // Use a minimal query to validate access to the Project; avoid union selections
            try {
              const projResp = await github.graphql(`
                query($login:String!, $number:Int!){
                  user(login:$login){ projectV2(number:$number){ id title } }
                }
              `, { login: owner, number });
              const proj = projResp.user && projResp.user.projectV2;
              if (!proj) {
                core.setFailed('Project not found or token lacks access. Ensure GH_PROJECT_TOKEN has project scope and the project exists.');
                return;
              }
              core.info(`Project resolved: ${proj.title} (${proj.id})`);
              core.info('Fields: Please verify in the UI that single-select fields exist with these options:');
              core.info('- Status: Todo, In Progress, Done');
              core.info('- Priority: P0, P1, P2, P3');
              core.info('- Area: lyrics, vocals, export, downloader, inference');
              core.info('The add-to-project workflow will use these fields if present.');
            } catch (e) {
              core.setFailed(`GraphQL access error: ${e}`);
            }
